version: "3.8"

networks:
  stock:
    driver: bridge

services:
  # Applications

  analytics:
    image: "analytics-service"
    container_name: "analytics"
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      - SERVER_PORT=9001
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_KEYCLOAK_SERVER_URL=http://stock-keycloak:8080
      - SPRING_KEYCLOAK_SERVER_EXTERNAL_URL=http://localhost:8080
      - ZIPKIN_HOST=zipkin
    networks:
      - stock

  basket:
    image: "basket-service"
    container_name: "basket"
    ports:
      - 9002:9002
      - 8002:8002
    environment:
      - SERVER_PORT=9002
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8002
      - SPRING_KEYCLOAK_SERVER_URL=http://stock-keycloak:8080
      - SPRING_KEYCLOAK_SERVER_EXTERNAL_URL=http://localhost:8080
      - ZIPKIN_HOST=zipkin
    networks:
      - stock

  catalog-command:
    image: "catalog-command-service"
    container_name: "catalog-command"
    ports:
      - 9003:9003
      - 8003:8003
    environment:
      - SERVER_PORT=9003
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8003
      - SPRING_KEYCLOAK_SERVER_URL=http://stock-keycloak:8080
      - SPRING_KEYCLOAK_SERVER_EXTERNAL_URL=http://localhost:8080
      - ZIPKIN_HOST=zipkin
    networks:
      - stock

  catalog-query:
    image: "catalog-query-service"
    container_name: "catalog-query"
    ports:
      - 9004:9004
      - 8004:8004
    environment:
      - SERVER_PORT=9004
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8004
      - SPRING_KEYCLOAK_SERVER_URL=http://stock-keycloak:8080
      - SPRING_KEYCLOAK_SERVER_EXTERNAL_URL=http://localhost:8080
      - ZIPKIN_HOST=zipkin
    networks:
      - stock

  order-processing:
    image: "order-processing-service"
    container_name: "order-processing"
    ports:
      - 9005:9005
      - 8005:8005
    environment:
      - SERVER_PORT=9005
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8005
      - SPRING_KEYCLOAK_SERVER_URL=http://stock-keycloak:8080
      - SPRING_KEYCLOAK_SERVER_EXTERNAL_URL=http://localhost:8080
      - ZIPKIN_HOST=zipkin
    networks:
      - stock

  payment:
    image: "payment-service"
    container_name: "payment"
    ports:
      - 9006:9006
      - 8006:8006
    environment:
      - SERVER_PORT=9006
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8006
      - SPRING_KEYCLOAK_SERVER_URL=http://stock-keycloak:8080
      - SPRING_KEYCLOAK_SERVER_EXTERNAL_URL=http://localhost:8080
      - ZIPKIN_HOST=zipkin
    networks:
      - stock

  basket2:
    image: "basket-service"
    container_name: "basket2"
    ports:
      - 9007:9007
      - 8007:8007
    environment:
      - SERVER_PORT=9007
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8007
      - SPRING_KEYCLOAK_SERVER_URL=http://stock-keycloak:8080
      - SPRING_KEYCLOAK_SERVER_EXTERNAL_URL=http://localhost:8080
      - ZIPKIN_HOST=zipkin
    networks:
      - stock

  basket3:
    image: "basket-service"
    container_name: "basket3"
    ports:
      - 9008:9008
      - 8008:8008
    environment:
      - SERVER_PORT=9008
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8008
      - SPRING_KEYCLOAK_SERVER_URL=http://stock-keycloak:8080
      - SPRING_KEYCLOAK_SERVER_EXTERNAL_URL=http://localhost:8080
      - ZIPKIN_HOST=zipkin
    networks:
      - stock

  catalog-query2:
    image: "catalog-query-service"
    container_name: "catalog-query2"
    ports:
      - 9009:9009
      - 8009:8009
    environment:
      - SERVER_PORT=9009
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8009
      - SPRING_KEYCLOAK_SERVER_URL=http://stock-keycloak:8080
      - SPRING_KEYCLOAK_SERVER_EXTERNAL_URL=http://localhost:8080
      - ZIPKIN_HOST=zipkin
    networks:
      - stock

  order-processing2:
    image: "order-processing-service"
    container_name: "order-processing2"
    ports:
      - 9010:9010
      - 8010:8010
    environment:
      - SERVER_PORT=9010
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8010
      - SPRING_KEYCLOAK_SERVER_URL=http://stock-keycloak:8080
      - SPRING_KEYCLOAK_SERVER_EXTERNAL_URL=http://localhost:8080
      - ZIPKIN_HOST=zipkin
    networks:
      - stock

  catalog-command2:
    image: "catalog-command-service"
    container_name: "catalog-command2"
    ports:
      - 9011:9011
      - 8011:8011
    environment:
      - SERVER_PORT=9011
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8011
      - SPRING_KEYCLOAK_SERVER_URL=http://stock-keycloak:8080
      - SPRING_KEYCLOAK_SERVER_EXTERNAL_URL=http://localhost:8080
      - ZIPKIN_HOST=zipkin
    networks:
      - stock

  catalog-command3:
    image: "catalog-command-service"
    container_name: "catalog-command3"
    ports:
      - 9012:9012
      - 8012:8012
    environment:
      - SERVER_PORT=9012
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8012
      - SPRING_KEYCLOAK_SERVER_URL=http://stock-keycloak:8080
      - SPRING_KEYCLOAK_SERVER_EXTERNAL_URL=http://localhost:8080
      - ZIPKIN_HOST=zipkin
    networks:
      - stock

  gateway:
    image: "gateway-service"
    container_name: "gateway"
    ports:
      - 9000:9000
      - 8000:8000
    environment:
      - SERVER_PORT=9000
      # Buildpacks environment variable to enable debug through a socket on port 8000
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8000
      - ANALYTICS_SERVICE_URL=http://analytics:9001
      - BASKET_SERVICE_URL=http://basket:9002
      - CATALOG_COMMAND_SERVICE_URL=http://catalog-command:9003
      - CATALOG_QUERY_SERVICE_URL=http://catalog-query:9004
      - ORDER_PROCESSING_SERVICE_URL=http://order-processing:9005
      - PAYMENT_SERVICE_URL=http://payment:9006
      - BASKET2_SERVICE_URL=http://basket2:9007
      - BASKET3_SERVICE_URL=http://basket3:9008
      - CATALOG_QUERY2_SERVICE_URL=http://catalog-query2:9009
      - ORDER_PROCESSING2_SERVICE_URL=http://order-processing2:9010
      - CATALOG_COMMAND2_SERVICE_URL=http://catalog-command2:9011
      - CATALOG_COMMAND3_SERVICE_URL=http://catalog-command3:9012
      - SPRING_REDIS_HOST=gateway-redis
      - SPRING_REDIS_PORT=6380
      - SPRING_KEYCLOAK_SERVER_URL=http://stock-keycloak:8080
      - SPRING_KEYCLOAK_SERVER_EXTERNAL_URL=http://localhost:8080
    networks:
      - stock