#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $STOCK_ORDER_DB_USER WITH PASSWORD '$STOCK_ORDER_DB_PASSWORD';
    CREATE DATABASE $STOCK_ORDER_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $STOCK_ORDER_DB_NAME TO $STOCK_ORDER_DB_USER;
    ALTER DATABASE $STOCK_ORDER_DB_NAME SET TIMEZONE='Europe/Amsterdam';
EOSQL