spring:
  application:
    name: e2e

  cloud:
    openfeign:
      client:
        config:
          default:
            readTimeout: 20000
            connectTimeout: 30000
          analytics:
            url: http://localhost:9000/analytics/api
          basket:
            url: http://localhost:9000/basket/api
          catalog-command:
            url: http://localhost:9000/catalog-command/api
          catalog-query:
            url: http://localhost:9000/catalog-query/api
          order-processing:
            url: http://localhost:9000/order-processing/api
          oauth2:
            url: http://localhost:8080

  data:
    axon:
      mongodb:
        uri: mongodb://${app.axon.mongodb.user}:${app.axon.mongodb.password}@${app.axon.mongodb.host}:${app.axon.mongodb.port}/${app.axon.mongodb.database}?authSource=admin
        database: ${app.axon.mongodb.database}

    basket:
      redis:
        password: ${app.basket.redis.password}
        host: ${app.basket.redis.host}
        port: ${app.basket.redis.port}

  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    catalog-query:
      url: jdbc:postgresql://${app.catalog-query.postgres.host}:${app.catalog-query.postgres.port}/${app.catalog-query.postgres.database}
      username: ${app.catalog-query.postgres.user}
      password: ${app.catalog-query.postgres.password}
      driver-class-name: org.postgresql.Driver
      hikari:
        connection-timeout: 2000 #ms
        maximum-pool-size: 5
    order-processing:
      url: jdbc:postgresql://${app.order-processing.postgres.host}:${app.order-processing.postgres.port}/${app.order-processing.postgres.database}
      username: ${app.order-processing.postgres.user}
      password: ${app.order-processing.postgres.password}
      driver-class-name: org.postgresql.Driver
      hikari:
        connection-timeout: 2000 #ms
        maximum-pool-size: 5

security:
  oauth2:
    client-id: stock-app
    grant-type: password
    username: admin
    password: admin

app:
  axon:
    mongodb:
      host: localhost
      port: 27017
      user: user
      password: pass
      database: axonframework

  basket:
    redis:
      host: localhost
      port: 6379
      password: pass

  catalog-query:
    postgres:
      host: localhost
      port: 5432
      database: catalogdb
      user: catalogdbuser
      password: dbpass

  order-processing:
    postgres:
      host: localhost
      port: 5432
      database: orderdb
      user: orderdbuser
      password: dbpass


